// Code generated by sdkcodegen; DO NOT EDIT.

package models

// RoleType 角色类型
type RoleType int32

// AccountRole
const (
	roleTypeNone   RoleType = iota // 0
	RoleTypeNormal                 // 1
	RoleTypeAdmin                  // 2
)

// Account 账号信息
type Account struct {
	DefaultModel `bson:",inline"`
	// Name 名称
	Name string `bson:"name" json:"name"`
	// RoleType 角色类型
	RoleType RoleType `bson:"role_type" json:"rt"`
} // @name Account

type Accounts []Account

// IsAdmin return true if is admin type
func (a *Account) IsAdmin() bool {
	return a.RoleType == RoleTypeAdmin
}
